"""m17 ai model catalog

Revision ID: 1a5ebca06d61
Revises: b1a2c3d4e5f6
Create Date: 2026-09-17 12:35:07.562917
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1a5ebca06d61'
down_revision: Union[str, Sequence[str], None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=20), server_default='chat', nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_price_per_mtok', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('output_price_per_mtok', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_function_calling', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', name='uq_ai_model_catalog_model_id')
    )
    op.create_index('ix_ai_model_catalog_vendor_mode', 'ai_model_catalog', ['vendor', 'mode'], unique=False)
    op.create_table('ai_model_catalog_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_model_catalog_sync')
    op.drop_index('ix_ai_model_catalog_vendor_mode', table_name='ai_model_catalog')
    op.drop_table('ai_model_catalog')
    # ### end Alembic commands ###
