"""M1 baseline

Revision ID: d8af657e840d
Revises: 
Create Date: 2026-08-24 16:33:09.307075
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260824_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_clients_name')
    )
    op.create_table('export_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('export_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('info_finding_count', sa.Integer(), nullable=False),
    sa.Column('warning_finding_count', sa.Integer(), nullable=False),
    sa.Column('error_finding_count', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_runs_export_version_id', 'export_runs', ['export_version_id'], unique=False)
    op.create_index('ix_export_runs_feed_source_id', 'export_runs', ['feed_source_id'], unique=False)
    op.create_table('export_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('export_run_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_source_id', 'version_number', name='uq_export_versions_source_version')
    )
    op.create_index('ix_export_versions_export_run_id', 'export_versions', ['export_run_id'], unique=False)
    op.create_index('ix_export_versions_feed_source_id', 'export_versions', ['feed_source_id'], unique=False)
    op.create_table('feed_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('active_pipeline_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feed_sources_client_id', 'feed_sources', ['client_id'], unique=False)
    op.create_table('module_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_module_pipelines_name_version')
    )
    op.create_index('ix_module_pipelines_feed_source_id', 'module_pipelines', ['feed_source_id'], unique=False)
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_plugins_name_version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('revocation_generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('error_stack_trace', sa.String(length=20000), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_feed_source_id', 'ingestion_runs', ['feed_source_id'], unique=False)
    op.create_table('module_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['module_pipelines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'position', name='uq_module_instances_pipeline_position')
    )
    op.create_index('ix_module_instances_pipeline_id', 'module_instances', ['pipeline_id'], unique=False)
    op.create_index('ix_module_instances_plugin_id', 'module_instances', ['plugin_id'], unique=False)
    op.create_table('plugin_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('feed_source_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("(scope = 'global' AND client_id IS NULL AND feed_source_id IS NULL) OR (scope = 'client' AND client_id IS NOT NULL AND feed_source_id IS NULL) OR (scope = 'feed_source' AND client_id IS NULL AND feed_source_id IS NOT NULL)", name='ck_plugin_configs_scope_owner'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_configs_client_id', 'plugin_configs', ['client_id'], unique=False)
    op.create_index('ix_plugin_configs_feed_source_id', 'plugin_configs', ['feed_source_id'], unique=False)
    op.create_index('ix_plugin_configs_plugin_id', 'plugin_configs', ['plugin_id'], unique=False)
    op.create_index('uq_plugin_configs_client_plugin_key', 'plugin_configs', ['plugin_id', 'client_id', 'key'], unique=True, postgresql_where=sa.text("scope = 'client' AND client_id IS NOT NULL AND feed_source_id IS NULL"))
    op.create_index('uq_plugin_configs_feed_source_plugin_key', 'plugin_configs', ['plugin_id', 'feed_source_id', 'key'], unique=True, postgresql_where=sa.text("scope = 'feed_source' AND client_id IS NULL AND feed_source_id IS NOT NULL"))
    op.create_index('uq_plugin_configs_global_plugin_key', 'plugin_configs', ['plugin_id', 'key'], unique=True, postgresql_where=sa.text("scope = 'global' AND client_id IS NULL AND feed_source_id IS NULL"))
    op.create_table('plugin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('feed_source_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'global' AND client_id IS NULL AND feed_source_id IS NULL) OR (scope = 'client' AND client_id IS NOT NULL AND feed_source_id IS NULL) OR (scope = 'feed_source' AND client_id IS NULL AND feed_source_id IS NOT NULL)", name='ck_plugin_data_scope_owner'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_data_client_id', 'plugin_data', ['client_id'], unique=False)
    op.create_index('ix_plugin_data_feed_source_id', 'plugin_data', ['feed_source_id'], unique=False)
    op.create_index('ix_plugin_data_plugin_id', 'plugin_data', ['plugin_id'], unique=False)
    op.create_index('uq_plugin_data_client_plugin_key', 'plugin_data', ['plugin_id', 'client_id', 'key'], unique=True, postgresql_where=sa.text("scope = 'client' AND client_id IS NOT NULL AND feed_source_id IS NULL"))
    op.create_index('uq_plugin_data_feed_source_plugin_key', 'plugin_data', ['plugin_id', 'feed_source_id', 'key'], unique=True, postgresql_where=sa.text("scope = 'feed_source' AND client_id IS NULL AND feed_source_id IS NOT NULL"))
    op.create_index('uq_plugin_data_global_plugin_key', 'plugin_data', ['plugin_id', 'key'], unique=True, postgresql_where=sa.text("scope = 'global' AND client_id IS NULL AND feed_source_id IS NULL"))
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocation_generation', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_token_hash', 'sessions', ['token_hash'], unique=True)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('staging_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_source_id', 'product_id', name='uq_staging_products_source_product')
    )
    op.create_index('ix_staging_products_feed_source_id', 'staging_products', ['feed_source_id'], unique=False)
    op.create_index('ix_staging_products_ingestion_run_id', 'staging_products', ['ingestion_run_id'], unique=False)
    op.create_table('quality_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_product_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staging_product_id'], ['staging_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_findings_ingestion_run_id', 'quality_findings', ['ingestion_run_id'], unique=False)
    op.create_index('ix_quality_findings_staging_product_id', 'quality_findings', ['staging_product_id'], unique=False)
    op.create_table('staging_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_product_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staging_product_id'], ['staging_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staging_history_staging_product_id', 'staging_history', ['staging_product_id'], unique=False)
    op.create_foreign_key('fk_feed_sources_active_pipeline_id', 'feed_sources', 'module_pipelines', ['active_pipeline_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_export_runs_feed_source_id', 'export_runs', 'feed_sources', ['feed_source_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_export_runs_export_version_id', 'export_runs', 'export_versions', ['export_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_export_versions_feed_source_id', 'export_versions', 'feed_sources', ['feed_source_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_export_versions_export_run_id', 'export_versions', 'export_runs', ['export_run_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_export_versions_export_run_id', 'export_versions', type_='foreignkey')
    op.drop_constraint('fk_export_versions_feed_source_id', 'export_versions', type_='foreignkey')
    op.drop_constraint('fk_export_runs_export_version_id', 'export_runs', type_='foreignkey')
    op.drop_constraint('fk_export_runs_feed_source_id', 'export_runs', type_='foreignkey')
    op.drop_constraint('fk_feed_sources_active_pipeline_id', 'feed_sources', type_='foreignkey')
    op.drop_index('ix_staging_history_staging_product_id', table_name='staging_history')
    op.drop_table('staging_history')
    op.drop_index('ix_quality_findings_staging_product_id', table_name='quality_findings')
    op.drop_index('ix_quality_findings_ingestion_run_id', table_name='quality_findings')
    op.drop_table('quality_findings')
    op.drop_index('ix_staging_products_ingestion_run_id', table_name='staging_products')
    op.drop_index('ix_staging_products_feed_source_id', table_name='staging_products')
    op.drop_table('staging_products')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_token_hash', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_plugin_data_global_plugin_key', table_name='plugin_data', postgresql_where=sa.text("scope = 'global' AND client_id IS NULL AND feed_source_id IS NULL"))
    op.drop_index('uq_plugin_data_feed_source_plugin_key', table_name='plugin_data', postgresql_where=sa.text("scope = 'feed_source' AND client_id IS NULL AND feed_source_id IS NOT NULL"))
    op.drop_index('uq_plugin_data_client_plugin_key', table_name='plugin_data', postgresql_where=sa.text("scope = 'client' AND client_id IS NOT NULL AND feed_source_id IS NULL"))
    op.drop_index('ix_plugin_data_plugin_id', table_name='plugin_data')
    op.drop_index('ix_plugin_data_feed_source_id', table_name='plugin_data')
    op.drop_index('ix_plugin_data_client_id', table_name='plugin_data')
    op.drop_table('plugin_data')
    op.drop_index('uq_plugin_configs_global_plugin_key', table_name='plugin_configs', postgresql_where=sa.text("scope = 'global' AND client_id IS NULL AND feed_source_id IS NULL"))
    op.drop_index('uq_plugin_configs_feed_source_plugin_key', table_name='plugin_configs', postgresql_where=sa.text("scope = 'feed_source' AND client_id IS NULL AND feed_source_id IS NOT NULL"))
    op.drop_index('uq_plugin_configs_client_plugin_key', table_name='plugin_configs', postgresql_where=sa.text("scope = 'client' AND client_id IS NOT NULL AND feed_source_id IS NULL"))
    op.drop_index('ix_plugin_configs_plugin_id', table_name='plugin_configs')
    op.drop_index('ix_plugin_configs_feed_source_id', table_name='plugin_configs')
    op.drop_index('ix_plugin_configs_client_id', table_name='plugin_configs')
    op.drop_table('plugin_configs')
    op.drop_index('ix_module_instances_plugin_id', table_name='module_instances')
    op.drop_index('ix_module_instances_pipeline_id', table_name='module_instances')
    op.drop_table('module_instances')
    op.drop_index('ix_ingestion_runs_feed_source_id', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('plugins')
    op.drop_index('ix_module_pipelines_feed_source_id', table_name='module_pipelines')
    op.drop_table('module_pipelines')
    op.drop_index('ix_feed_sources_client_id', table_name='feed_sources')
    op.drop_table('feed_sources')
    op.drop_index('ix_export_versions_feed_source_id', table_name='export_versions')
    op.drop_index('ix_export_versions_export_run_id', table_name='export_versions')
    op.drop_table('export_versions')
    op.drop_index('ix_export_runs_feed_source_id', table_name='export_runs')
    op.drop_index('ix_export_runs_export_version_id', table_name='export_runs')
    op.drop_table('export_runs')
    op.drop_table('clients')
    # ### end Alembic commands ###
